appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: WX2UuOyba3iNEPfvc3pZ9TGURWisQM23D8SXVR2MEdbs5hBokh2u9u0fFrXloYwyzvNcQDju13m9UQ/KegJIb6bcnaJdrZNhZjyMtlhupJYEtvWeAJkLKjy/mooTwIBF2j2Gk2snW8rBI3/Tw8oX1CJL8mPhcpPFz+MyWGzYJSgY9hVVaPeBxgH+3abjSTgnylun0FEg/rTn6LiqC3L3RfeEnIz2FUA7I6BJUi8G76pbKceWksM6nS7TqcJ0kTOeMQO34Zxw5Zt09Shhh7zMy071mwtxuy7B0WxkmwGE0Xb+yUbQwWUDhB7wGcrnAr3ZeKsqP9k8wjM06uzZH1u0jh4upUoLhe0M244U4XHHUGJCs2HOLzqkvsPRzITJpSqkOHc+pTeqgGeLhnrpxOOMNrnyRzWYY0nMqdQT/+/91MEK6c1BYCICiSwectkEIoqrB8LiAT3JjTzUw+ivTjSCgIuJcnmTm9G/vzCbxaRtLDZ8j50pD8tfM0bujRVOqKTxTqtDHSoR0uhYsis7ATg+PoV3jzRXUhxmsoDFDz8wLiqkYdL0zEPG+QKRdX1OGRWELnyLGo15sDkLTZJTZ6/DucJDJ1e06RsdLDOTuOhVjaZ0CxfV/yCw9bxgRILqaelJnPYk4T1on0xRlJYe9nrv1ssIEUqi0rbJIxlNSUqVZT4=}
provider:
  win: azure
conda_forge_output_validation: true
