travis:
  secure:
    BINSTAR_TOKEN: KNfv0z9ozFDdfbW2SjzFQYAFlanY357Yi2I6S5UE2yZz6MwoPNm8cRNUMpmjXXfQFuD8BbMAToIyBhfN6z/AE459Qo2aL8Obs+2QZPN6leCkhgX3QBD8jP0ScsU6R4QmJDIVzJrtkQF72IhzQc2LA68iam7aAuh4MsK+VvYEiQmZ01bGor3RKwJ7mGehrHndJ2VAn9d6g+lKI42qTP1BbYma1eaJLFgUcgzazoDd8Oixyqn4LELOF3VQRtKoX9JiB3fBM8wY4xk5+TQPQeM6fW2PJ6+ZmRop6EWgkzRN+qKinxcjAQO7MmUtpcRF8EczL0W8EK6GdALHjqh6/Qcwt+DgG0HecWuGGOkf03ofJAYS+/u/mhREtMjGu20Zpm+6Fpndl0grLj6GBlqRDK3WpeZkZSv9LkNjkKgrtxRjLOeIOHTOgQW8CfgfM9rD1EBIY0IfQtpxLbw++HrhjN7nfdwHsB3HZ9aqgqv3JRUhjRvo4fP4xtxuBB0vNyevVgTYepios0CNsRUrWYbMv3e20AaSzi5A78kbhRigBB/Zsxt8J7kGrWu43IQ4ybN+7rCEmXMHmhs2ScWq0PgCHgm/vu6+oD/FNPWX6WVTDNmhgjkyfOPisFcKAJ88s7/82B+DWbFrM4kcX/rJomgr+H7z3plo9acR83GRTT07X4pn0/k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
